/**
 * The module defines {@link Task} class
 * @module Task
 * @category Database
*/
import { randomUUID } from "crypto"
/** 
 * Class representing a Task.
 * @category Database
 */
export default class Task{
  /** The id of Task. Autogenerated with uuid. Can be null. */
  id: string | null

  /** The Title of Task. */
  title: string

  /** The Order of Task. */
  order: number

  /** The Description of Task. */
  description: string

  /** User`s id of Task. */
  userId: string | null

  /** Board`s id of Task. */
  boardId: string | null

  /** Column`s id of Task. */
  columnId: string | null

  /**
   * Create a Task.
   * @param title - The title of Task.
   * @param oredr - The order of Task.
   * @param description - The description of Task.
   * @param userId - The id of User.
   * @param boardId - The id of Board.
   * @param columnId - The id of Column.
   * @returns Instance of Task.
   * @category Task
   */

  constructor({ 
        title = "Autotest task",
        order = 0,
        description = "Lorem ipsum",
        userId = null,
        boardId = null,
        columnId = null, } = {} as Task)
  {
      this.id =  randomUUID()
      this.title = title
      this.order = order
      this.description = description
      this.userId = userId
      this.boardId = boardId
      this.columnId = columnId
  }
}