/**
 * The module defines {@link User} class
 * @module User
 * @category Database
*/

import { randomUUID } from "crypto"

/** 
 * Class representing a User.
 * @category Database
 */

export default class User {
    /** The id of User. Autogenerated with uuid. Can be null. */
    id: string | null

    /** The name of user. */
    name: string

    /** The login of user. */
    login: string

    /** The password of user. Optional. */
    password?: string

  /**
   * Create a User.
   * @param name - The name of User.
   * @param login - The login of User.
   * @param password - The password of User.
   * @returns Instance of User.
   * @category User
   */

  constructor({
    name = "TEST_USER",
    login = "test_user",
    password = "T35t_P@55w0rd"} = {} as User) 
  {  
    this.id = randomUUID()
    this.name = name
    this.login = login
    this.password = password
  }

  static toResponse(user: User): User {
    const { id, name, login } = user
    return { id, name, login }
  }
}