version: "3.3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-database
    networks:
      - rsschool-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
volumes:
  db_data:
networks:
  rsschool-network:
    driver: bridge