# Better perfomance: smaller image size
FROM alpine:3.15
RUN apk add --update nodejs npm

#FROM node:16-alpine3.15
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
EXPOSE ${PORT}
CMD ["npm", "start"]