/**
 * The module defines {@link Board} class
 * @module Board
 * @category Database
*/
import { randomUUID } from "crypto"
/** 
 * Type representing a Column.
 * @category Database
 */
export type ColumnsType = {
  /** The id of Column. Autogenerated with uuid. Can be null. */
  id: string | null
  /** The Title of Column. */
  title: string
  /** The order of Column. */
  order: number
}
/** 
 * Class representing a Board.
 * @category Database
 */
export class Board {
  /** The id of Board. Autogenerated with uuid. Can be null. */
  id: string | null

  /** The Title of Column. */
  title: string

  /** The array of Columns. */
  columns: ColumnsType[]

  /**
   * Create a Board.
   * @param title - The title of Board.
   * @param columns - The array of Columns.
   * @returns Instance of Board.
   * @category Board
   */

  constructor({
        title = "Autotest board",
        columns = [
          { id:null, title: 'Backlog', order: 1 },
          { id:null, title: 'Sprint', order: 2 }
        ] } = {} as Board)
        {
              this.id = randomUUID()
              this.title = title
              this.columns = columns
        }
}